### PR TITLE
Implemented the PKCE authorization flow for the web platform.

### PR DESCRIPTION
**Pull request by itsMatoosh**
Replaced the Implicit Grant authorization flow with the new [Authorization Code With PKCE authorization flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce). This allows the plugin to automatically refresh the authorization in the background every time the access token expires, instead of having to open the authorization prompt each time like before. 
This requires a change to the web authentication redirect setup, therefore I updated the README with the new instructions.

### CODE REVIEW

**Comment by brim-borium** [comment]
Don't know if I find the time to review this at the moment @Joran-Dob I assigned you. I think we should merge this before #42

**Comment by itsMatoosh** [comment]
Found an issue with this. I'll work it out and request another review.

**Comment by brim-borium** [comment]
> Found an issue with this. I'll work it out and request another review.

Alright can you review #42 so I can merge it and we can publish a new version?

**Comment by itsMatoosh** [comment]
Fixed! This is now ready to merge.

**Review by brim-borium — APPROVED** [review]

**Comment by brim-borium** [comment]
@itsMatoosh you can merge this so this will also available in the new release

**Pull request merged**
