### PR TITLE
Fetch iOS SDK automatically

### PR DESCRIPTION
**Pull request by fotiDim**

### CODE REVIEW

**Review by brim-borium — COMMENTED** [review]
Just for my general understanding
Will the script always execute or just one time?
What happens when the sdk already exists?

**Comment by fotiDim** [comment]
It executed each time `pod install` is executed. You can think of it as equivalent to `gradle build`. In practice `flutter run` calls it.

> Just for my general understanding
> Will the script always execute or just one time?
> What happens when the sdk already exists?

I made an improvement based on your point. I remove the framework at the beginning of script and then recreate it each time.

**Comment by brim-borium** [comment]
> It executed each time `pod install` is executed. You can think of it as equivalent to `gradle build`. In practice `flutter run` calls it.
> 
> > Just for my general understanding
> > Will the script always execute or just one time?
> > What happens when the sdk already exists?
> 
> I made an improvement based on your point. I remove the framework at the beginning of script and then recreate it each time.

Wouldn't it be better to not run again if it already existst. So we don't have to download the sdk everytime we call flutter run?

**Comment by fotiDim** [comment]
I did some testing and it seems even `pod install` does not run it each and every time. It only happens on a fresh install or after explicitly running `pod clean`. 

Also `flutter clean` does not seem to trigger `pod clean`.

**Review by brim-borium — APPROVED** [review]

**Comment by itsMatoosh** [comment]
I've tried using this implementation, but the SDK doesn't download for me automatically. I tried deleting the Pods/ directory, running flutter clean, and flutter build, however none of them seemed to download the SDK. When attempting to build, I get the following error:

```
Running pod install... 
Running Xcode build...                                                  
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    /Users/matoosh/Coding/jux_flutter/ios/.symlinks/plugins/spotify_sdk/ios/ios-sdk/SpotifyiOS.framework/module.map:2:8: error: header
    'Headers/SpotifyiOS.h' not found
    header "Headers/SpotifyiOS.h"
           ^
    /Users/matoosh/.pub-cache/git/spotify_sdk-76ba13d618ddb8943d0fdb7c2ddb9fb6048fae24/ios/Classes/ConnectionStatusHandler.swift:1:8: error:
    could not build Objective-C module 'SpotifyiOS'
    import SpotifyiOS
           ^
    Command MergeSwiftModule failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPad Pro (12.9-inch) (4th generation).
```
Any idea why this is happening?

**Comment by fotiDim** [comment]
Is it a fresh or an existing project?
Try `cd example/ios && pod clean && pod install`

**Comment by itsMatoosh** [comment]
It's an existing project, I just updated the spotify_sdk dependency to point to the master branch of this repo.
Doing `cd /ios && pod cache clean -all && pod install` doesn't fix the issue. Is there a way to force this prepare script to run?

**Comment by fotiDim** [comment]
Are you under MacOS?
What if you run the `prepare-iOS-SDK.sh` script manually?

**Comment by itsMatoosh** [comment]
To get this to work, I had to make a change in the script. The `wget https://github.com/spotify/ios-sdk/archive/v1.2.2.zip` command is not available on MacOS, so I replaced it with `curl -OL https://github.com/spotify/ios-sdk/archive/v1.2.2.zip`. `curl -OL` has the same functionality as `wget` in this case. After making the change, I had to manually run `prepare-iOS-SDK.sh` from the spotify_sdk package folder.
I think you should add a check for the client OS in the script, and if it's MacOS, use the curl command to download the SDK.

**Comment by fotiDim** [comment]
OK i see. I am also on MacOS. The script is only meant to be used on MacOS
as you cannot compile iOS apps on Linux or Windows.

I have probably manually installed wget at some point.

After your fix, running pod clean and then flutter run should have been
enough.

Do you want to make a PR for it?

**Comment by itsMatoosh** [comment]
Ok, I see, I'll make a PR then

**Pull request merged**
